
stages:
  - generics
  - challenges
  - platform
  - publish
  - deploy

variables:
  build_version: $CI_PIPELINE_IID

include:
  - local: '/automation/docker.templates.gitlab-ci.yml'
  - local: '/generics/build.gitlab-ci.yml'
  - local: '/challenges/training-platform/build.gitlab-ci.yml'
  - local: '/automation/web.gitlab-ci.yml'
  - local: '/automation/telegram.gitlab-ci.yml'
