
telegram:
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  script:
    - git changelog --format telegram-html --incoming >chlog
    - announce-telegram chlog "$CHAT_IDS"
  only:
    - main

web-lint:
  image: python:latest
  script:
    - make web/lint
  only:
    - merge_requests
