version: "3.3"

services:

  server:
    image: ctf-platform:latest
    ports:
      - "8080:8000"
    volumes:
      - ./data/storage:/app/data
      - ./data/logs:/app/logs
    env_file: web/secret.properties
