### Prerequesites :
  # ansible-galaxy collection install community.windows
  # ansible-galaxy collection install ansible.windows

- name: 2nd step - configure Windows 10 machine
  hosts: model_zero_logon_windows_10
  tasks:

    - name: Change Computer Name
      ansible.windows.win_hostname:
        name: Windows-Test
      register: change_name

    - name: Reboot
      ansible.windows.win_reboot:
      when: change_name.changed


    ## Join domain domain.rsr

    - name: Set a single address on the adapter named Ethernet
      ansible.windows.win_dns_client:
        adapter_names: Ethernet0
        dns_servers: 172.21.202.96


    - name : Join domain.rsr
      ansible.windows.win_domain_membership:
        dns_domain_name: domain.rsr
        domain_admin_user: rsr@domain.rsr
        domain_admin_password: rsrSecurePassw0rd
        state: domain
      register: domain_state

    - name: Reboot
      ansible.windows.win_reboot:
      when: domain_state.reboot_required


    ## Create the flag

    - name: Create the flag file
      ansible.windows.win_copy:
        src: myfiles/flag.jpg
        dest: C:\flag.jpg



    ## Set up inside the private network

    - name: Set a single address on the adapter named Ethernet
      ansible.windows.win_dns_client:
        adapter_names: Ethernet0
        dns_servers: 192.168.1.50

    - name: Set up static IP address
      win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet0' | New-NetIpAddress -IpAddress 192.168.1.120 -PrefixLength 24 -DefaultGateway 192.168.1.1"
      async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
      poll: 0

