
.generics:
  stage: generics
  needs: [ ]
  parallel:
    matrix:
      - generic: [ generic-alpine-3.12 ]
  script:
    - set -o allexport; . ~/secret.properties; set +o allexport
    - cd "generics/$generic"
    - test -e prepare-build.sh && ./prepare-build.sh
    - packer build -force build.pkr.hcl

generics:test:
  extends: [ .generics ]
  tags:
    - test-server
  only:
    - merge_requests

generics:staging:
  extends: [ .generics ]
  tags:
    - staging-server
  only:
    - main

generics:production:
  extends: [ .generics ]
  tags:
    - production-server
  only:
    - tags
