
.generics:
  stage: generics
  needs: [ ]
  parallel:
    matrix:
      - generic: [ generic-alpine-3.12, generic-kali-2021.4 ]
  script:
    - set -o allexport; . ~/secret.properties; set +o allexport
    - cd "generics/$generic"
    - ../packer-build.sh

generics:test:
  extends: [ .generics ]
  tags:
    - test-server
  only:
    - merge_requests

generics:staging:
  extends: [ .generics ]
  tags:
    - staging-server
  only:
    - main

generics:production:
  extends: [ .generics ]
  tags:
    - production-server
  only:
    - tags
